version: '3.9'
services:
  laravel:
    image: dimmaryanto93/laravel-monolith-apps:v1
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
