apiVersion: v1
kind: Pod
metadata:
  name: laravel
  labels:
    app: laravel
    tier: monolith
spec:
  initContainers:
    - name: artisan-migrate
      image: 192.168.88.50:8086/udemy/laravel-monolith-apps:v3
      command: [".docker/php-artisan-migrate"]
      ports:
        - containerPort: 80
      env:
        - name: APP_URL
          value: ""
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
  containers:
    - name: laravel
      image: 192.168.88.50:8086/udemy/laravel-monolith-apps:v3
      ports:
        - containerPort: 80
          name: http
      env:
        - name: APP_URL
          value: ""
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 1500m
          memory: 1Gi
      startupProbe:
        httpGet:
          port: http
          path: /actuator/health/readiness
          scheme: HTTP
        initialDelaySeconds: 2
        timeoutSeconds: 1
      livenessProbe:
        httpGet:
          port: http
          path: /actuator/health/liveness
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 3
        failureThreshold: 2
      imagePullPolicy: Always
  restartPolicy: Always
