apiVersion: v1
kind: Pod
metadata:
  name: laravel
  labels:
    app: laravel
    tier: monolith
spec:
  containers:
    - name: laravel
      image: 192.168.88.50:8086/udemy/laravel-monolith-apps:v1
      ports:
        - containerPort: 80
      env:
        - name: APP_URL
          value: ""
        - name: DB_HOST
          value: mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: mysql-config
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 1500m
          memory: 1Gi
      imagePullPolicy: Always
  restartPolicy: Always
