apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  selector:
    app: laravel
    tier: monolith
  ports:
    - port: 8000
      targetPort: 80
      name: http
      protocol: TCP
  type: NodePort
