apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: mysql-config
            optional: false
        - secretRef:
            name: mysql-secret
            optional: false
  restartPolicy: Always
